language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - yarn build
  - yarn test
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
install:
  - yarn
  - nohup yarn run testrpc &
