language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - yarn build
  - yarn test
notifications:
  slack: kleros:Ub8n81EgKJ3iRrMDyWyQIVJp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
install:
  - yarn
  - nohup yarn run testrpc &
https://github.com/kleros/kleros-api.git
